# -*- coding: utf-8 -*-
COVER_IMAGES_MISSING = {
    "qu_modelos": {"file": "qu_modelos_capa.png", "caption": "Bohr-model v Oxygen", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Bohr-model_v_Oxygen.png?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "mt_conj": {"file": "mt_conj_capa.png", "caption": "Circuito", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/3/34/Circuito.png?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "mt_matriz": {"file": "mt_matriz_capa.png", "caption": "MatrixMultiplication", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/e/e5/MatrixMultiplication.png?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "mt_stat": {"file": "mt_stat_capa.gif", "caption": "Normal distribution and scales", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Normal_distribution_and_scales.gif?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "ing_lex": {"file": "ing_lex_capa.jpg", "caption": "Acordo ortografico PT", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Acordo_ortografico_PT.jpg?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "esp_comp": {"file": "esp_comp_capa.jpg", "caption": "4th Alpini Rgt Rappeling from an AB205", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/4th_Alpini_Rgt_Rappeling_from_an_AB205.jpg?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "esp_sem": {"file": "esp_sem_capa.png", "caption": "Rede Semântica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Rede_Sem%C3%A2ntica.png?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "soc_est": {"file": "soc_est_capa.jpg", "caption": "Assembléia Legislativa do Rio de Janeiro - Rio de Janeiro, RJ - panoramio (1)", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/5/54/Assembl%C3%A9ia_Legislativa_do_Rio_de_Janeiro_-_Rio_de_Janeiro%2C_RJ_-_panoramio_%281%29.jpg?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
}
    "pt_text": {"file": "pt_text_capa.jpeg", "caption": "Olivetti Lettera 22 by LjL", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Olivetti_Lettera_22_by_LjL.jpeg?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "pt_morfo": {"file": "pt_morfo_capa.png", "caption": "Nt-compilador", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Nt-compilador.png?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
    "filo_log": {"file": "filo_log_capa.jpg", "caption": "Aristoteles", "source": "Wikipédia (Português do Brasil)", "source_url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Aristoteles.jpg?utm_source=pt.wikipedia.org&utm_campaign=imageinfo&utm_content=original"},
