# -*- coding: utf-8 -*-
"""Imagens de capa da Wikipédia (Português do Brasil) para todos os PDFs.

Legendas em PT-BR descrevendo o conteudo educacional de cada imagem.
"""

COVER_IMAGES = {
    # Biologia
    "bi_intro": {"file": "bi_intro_capa.jpg", "caption": "Estrutura tridimensional de uma proteína — estudo da Biologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_cito": {"file": "bi_cito_capa.png", "caption": "Microscopia de cortiça observada por Robert Hooke — descoberta da célula", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_metab": {"file": "bi_metab_capa.png", "caption": "Estrutura da hemoglobina — proteína essencial ao metabolismo", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_embrio": {"file": "bi_embrio_capa.png", "caption": "Estágios iniciais do desenvolvimento embrionário", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_histo": {"file": "bi_histo_capa.jpg", "caption": "Microscopia eletrônica de tecido muscular esquelético humano", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_eco": {"file": "bi_eco_capa.jpg", "caption": "Ecossistema tropical — biodiversidade e relações ecológicas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_taxo": {"file": "bi_taxo_capa.jpg", "caption": "Systema Naturae de Lineu — classificação dos seres vivos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_micro": {"file": "bi_micro_capa.jpg", "caption": "Louis Pasteur em seu laboratório — pioneiro da microbiologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_bota": {"file": "bi_bota_capa.png", "caption": "Estrutura celular vegetal — objeto de estudo da botânica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_zoo": {"file": "bi_zoo_capa.jpg", "caption": "Diversidade do reino animal — zoologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_gene": {"file": "bi_gene_capa.jpg", "caption": "Genealogia e hereditariedade — estudo da genética", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_evo": {"file": "bi_evo_capa.png", "caption": "Molécula de DNA — base molecular da evolução", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "bi_saude": {"file": "bi_saude_capa.jpg", "caption": "Estudo histórico da varíola — saúde pública e doenças infecciosas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Quimica
    "qu_atomo": {"file": "qu_atomo_capa.jpg", "caption": "Resolução atômica de superfície de ouro — estrutura do átomo", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_modelos": {"file": "qu_modelos_capa.png", "caption": "Modelo atômico de Bohr — níveis de energia do elétron", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_tabela": {"file": "qu_tabela_capa.jpg", "caption": "Tabela periódica dos elementos químicos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_ligacoes": {"file": "qu_ligacoes_capa.gif", "caption": "Ligação covalente entre átomos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_inorg": {"file": "qu_inorg_capa.png", "caption": "Balanço de laboratório — funções inorgânicas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_reacoes": {"file": "qu_reacoes_capa.jpg", "caption": "Reação entre ácido clorídrico e amônia — reações químicas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_calc": {"file": "qu_calc_capa.png", "caption": "Cálculos estequiométricos — proporções nas reações", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_soluc": {"file": "qu_soluc_capa.png", "caption": "Solução de permanganato de potássio — concentração de soluções", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_equil": {"file": "qu_equil_capa.png", "caption": "Equilíbrio químico e catálise — cinética das reações", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_eletro": {"file": "qu_eletro_capa.jpg", "caption": "Pilha alcalina — exemplo de célula eletroquímica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_termo": {"file": "qu_termo_capa.png", "caption": "Calor e energia nas reações — termoquímica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_org": {"file": "qu_org_capa.png", "caption": "Estrutura do ácido acético — composto orgânico", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "qu_amb": {"file": "qu_amb_capa.jpg", "caption": "Antoine Lavoisier — pai da química moderna e estudos ambientais", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Fisica
    "fi_grand": {"file": "fi_grand_capa.jpg", "caption": "Balança analítica — medição de grandezas físicas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_cinem": {"file": "fi_cinem_capa.gif", "caption": "Movimento orbital — estudo da cinemática", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_dinam": {"file": "fi_dinam_capa_v2.jpg", "caption": "Forças e aceleração — segunda lei de Newton", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_hidro": {"file": "fi_hidro_capa.png", "caption": "Forças em fluidos — princípios da hidrostática", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_termo": {"file": "fi_termo_capa_v2.png", "caption": "Dilatação térmica e calorimetria — termologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_optica": {"file": "fi_optica_capa.png", "caption": "Ângulo de aceitação em fibras ópticas — óptica geométrica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_onda": {"file": "fi_onda_capa.gif", "caption": "Modos de vibração de uma membrana — ondulatória", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_eletrost": {"file": "fi_eletrost_capa.png", "caption": "Campo elétrico entre cargas — eletrostática", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_eletrodin": {"file": "fi_eletrodin_capa.jpg", "caption": "Corrente elétrica e circuitos — eletrodinâmica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_eletromag": {"file": "fi_eletromag_capa.jpg", "caption": "Eletroímã — indução e campo magnético", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "fi_moderna": {"file": "fi_moderna_capa.jpg", "caption": "Física moderna — relatividade e mecânica quântica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Matematica
    "mt_arit": {"file": "mt_arit_capa.png", "caption": "Operações aritméticas — fundamentos da matemática", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_conj": {"file": "mt_conj_capa.png", "caption": "Diagrama de Venn — teoria dos conjuntos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_func": {"file": "mt_func_capa.png", "caption": "Gráfico de função — estudo das funções matemáticas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_geoplan": {"file": "mt_geoplan_capa.jpg", "caption": "Figuras geométricas planas — geometria euclidiana", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_geoesp": {"file": "mt_geoesp_capa.gif", "caption": "Sólidos geométricos — geometria espacial", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_matriz": {"file": "mt_matriz_capa.png", "caption": "Matriz matemática — álgebra linear", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_trigo": {"file": "mt_trigo_capa.jpg", "caption": "Ciclo trigonométrico — relações trigonométricas", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_comb": {"file": "mt_comb_capa.png", "caption": "Fatorial e análise combinatória — contagem", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_stat": {"file": "mt_stat_capa.gif", "caption": "Gráfico estatístico — análise de dados", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "mt_geoanal": {"file": "mt_geoanal_capa.jpg", "caption": "Plano cartesiano — geometria analítica", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Portugues
    "pt_com": {"file": "pt_com_capa.jpg", "caption": "Comunicação e linguagem — elementos da comunicação", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_sem": {"file": "pt_sem_capa.png", "caption": "Semântica — estudo do significado das palavras", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_text": {"file": "pt_text_capa.jpeg", "caption": "Redação dissertativa — produção textual", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_morfo": {"file": "pt_morfo_capa.png", "caption": "Análise sintática — estrutura das orações", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_sint": {"file": "pt_sint_capa.jpg", "caption": "Gramática portuguesa — sintaxe do período composto", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_lit": {"file": "pt_lit_capa.jpg", "caption": "Literatura brasileira — tradição literária do Brasil", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "pt_obras": {"file": "pt_obras_capa.png", "caption": "Obras literárias — leitura e interpretação", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Ingles
    "ing_leit": {"file": "ing_leit_capa.jpg", "caption": "Reading comprehension — leitura e interpretação em inglês", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "ing_lex": {"file": "ing_lex_capa.jpg", "caption": "English vocabulary — léxico e vocabulário", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "ing_gram": {"file": "ing_gram_capa_v2.png", "caption": "English grammar — gramática da língua inglesa", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Espanhol
    "esp_comp": {"file": "esp_comp_capa.jpg", "caption": "Comprensión lectora — leitura em espanhol", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "esp_sem": {"file": "esp_sem_capa_v2.jpg", "caption": "Léxico e semântica em espanhol", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "esp_gram": {"file": "esp_gram_capa.jpg", "caption": "Gramática espanhola — estrutura da língua", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Historia
    "his_antigo": {"file": "his_antigo_capa.png", "caption": "Pirâmide do Egito — mundo antigo", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "his_medieval": {"file": "his_medieval_capa.png", "caption": "Castelo medieval — feudalismo e Idade Média", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "his_moderna": {"file": "his_moderna_capa.jpg", "caption": "Caravela portuguesa — grandes navegações", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "his_contemp": {"file": "his_contemp_capa.jpg", "caption": "Revolução Francesa — Idade Contemporânea", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "his_brasil": {"file": "his_brasil_capa.jpg", "caption": "História do Brasil contemporâneo", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "his_ma": {"file": "his_ma_capa.jpg", "caption": "Centro histórico de São Luís — história do Maranhão", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Geografia
    "geo_fis": {"file": "geo_fis_capa.jpg", "caption": "Estrutura interna da Terra — geografia física", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "geo_hum": {"file": "geo_hum_capa.gif", "caption": "Urbanização — geografia humana", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "geo_ma": {"file": "geo_ma_capa_v2.jpg", "caption": "Centro histórico de São Luís — geografia do Maranhão", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "geo_cont": {"file": "geo_cont_capa.jpg", "caption": "Desenvolvimento sustentável — temas contemporâneos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Filosofia
    "filo_cult": {"file": "filo_cult_capa.png", "caption": "Cultura e símbolos — filosofia da cultura", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_con": {"file": "filo_con_capa.jpg", "caption": "Método científico — teoria do conhecimento", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_filos": {"file": "filo_filos_capa.jpg", "caption": "Acrópole de Atenas — origem da filosofia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_log": {"file": "filo_log_capa.jpg", "caption": "Lógica aristotélica — silogismo e raciocínio", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_est": {"file": "filo_est_capa.jpg", "caption": "Arte renascentista — estética e filosofia da arte", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_pol": {"file": "filo_pol_capa.jpg", "caption": "Democracia ateniense — filosofia política", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "filo_et": {"file": "filo_et_capa.jpg", "caption": "Direitos humanos — ética e cidadania", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    # Sociologia
    "soc_surg": {"file": "soc_surg_capa.jpg", "caption": "Revolução Industrial — contexto do surgimento da sociologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_class": {"file": "soc_class_capa.jpg", "caption": "Sociologia clássica — Durkheim, Marx e Weber", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_conc": {"file": "soc_conc_capa.jpg", "caption": "Socialização e instituições sociais — conceitos básicos", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_mud": {"file": "soc_mud_capa.jpg", "caption": "Desigualdade social — estratificação e mobilidade", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_viol": {"file": "soc_viol_capa.jpg", "caption": "Violência urbana — sociologia da violência", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_cult": {"file": "soc_cult_capa.jpg", "caption": "Cultura de massa — indústria cultural e ideologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_trab": {"file": "soc_trab_capa.jpg", "caption": "Linha de montagem — trabalho e sociedade", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_est": {"file": "soc_est_capa.jpg", "caption": "Estado e soberania — poder e governo", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
    "soc_cont": {"file": "soc_cont_capa.jpg", "caption": "Globalização — temas contemporâneos da sociologia", "source": "Wikipédia (Português do Brasil)", "source_url": "https://pt.wikipedia.org"},
}
