"""Dados iniciais: edital simplificado + questões de treino no padrão PAES.

IMPORTANTE: questões abaixo são ORIGINAIS para treino alinhado ao edital.
Não são reproduções de provas oficiais. Frequências usam anos atribuídos
no seed para demonstrar o motor estatístico; ao importar provas oficiais,
reprocesse a base.
"""

from __future__ import annotations

import json
from typing import Any

from db import db, init_db
from seed_expand import EXTRA_SYLLABUS, build_extra_questions

SYLLABUS: list[dict[str, Any]] = [
    {"id": "bio-gen", "subject": "Biologia", "topic": "Genética", "subtopic": "Mendel", "weight": 1.4},
    {"id": "bio-eco", "subject": "Biologia", "topic": "Ecologia", "subtopic": "Cadeias alimentares", "weight": 1.2},
    {"id": "bio-cit", "subject": "Biologia", "topic": "Citologia", "subtopic": "Membrana", "weight": 1.3},
    {"id": "bio-fisio", "subject": "Biologia", "topic": "Fisiologia humana", "subtopic": "Sistemas", "weight": 1.5},
    {"id": "mat-fun", "subject": "Matemática", "topic": "Funções", "subtopic": "Exponencial", "weight": 1.3},
    {"id": "mat-geo", "subject": "Matemática", "topic": "Geometria analítica", "subtopic": "Reta e circunferência", "weight": 1.6},
    {"id": "mat-prob", "subject": "Matemática", "topic": "Probabilidade", "subtopic": "Eventos", "weight": 1.2},
    {"id": "qui-est", "subject": "Química", "topic": "Estequiometria", "subtopic": "Mol", "weight": 1.4},
    {"id": "qui-org", "subject": "Química", "topic": "Química orgânica", "subtopic": "Funções", "weight": 1.3},
    {"id": "fis-cin", "subject": "Física", "topic": "Cinemática", "subtopic": "MRU/MRUV", "weight": 1.2},
    {"id": "fis-ele", "subject": "Física", "topic": "Eletrodinâmica", "subtopic": "Circuitos", "weight": 1.3},
    {"id": "pt-int", "subject": "Língua Portuguesa e Literatura", "topic": "Interpretação de texto", "subtopic": "Funções da linguagem", "weight": 1.7},
    {"id": "pt-coe", "subject": "Língua Portuguesa e Literatura", "topic": "Coesão e coerência", "subtopic": "Conectivos", "weight": 1.5},
    {"id": "pt-lit", "subject": "Língua Portuguesa e Literatura", "topic": "Literatura", "subtopic": "Escolas literárias", "weight": 1.4},
    {"id": "his-br", "subject": "História", "topic": "Brasil República", "subtopic": "Século XX", "weight": 1.2},
    {"id": "geo-br", "subject": "Geografia", "topic": "Geografia do Brasil", "subtopic": "Nordeste", "weight": 1.3},
    {"id": "fil-eti", "subject": "Filosofia", "topic": "Ética", "subtopic": "Teorias morais", "weight": 1.0},
    {"id": "soc-cul", "subject": "Sociologia", "topic": "Cultura e sociedade", "subtopic": "Identidade", "weight": 1.0},
]

# Questões de treino com modo professor (7 blocos de metadados).
QUESTIONS: list[dict[str, Any]] = [
    {
        "id": "bio-2017-01",
        "year": 2017,
        "subject": "Biologia",
        "topic": "Genética",
        "subtopic": "Mendel",
        "statement": "Em um cruzamento mendeliano clássico entre dois indivíduos heterozigotos (Aa) para um gene autossômico com dominância completa, a probabilidade de nascer um descendente com fenótipo recessivo é:",
        "options": ["0%", "25%", "50%", "75%", "100%"],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["mendel", "probabilidade"],
        "syllabus_id": "bio-gen",
        "resolution": "1) Pais Aa x Aa produzem gametas A e a em proporção 1:1.\n2) Combinações zigóticas: AA, Aa, Aa, aa (proporção 1:2:1).\n3) Apenas aa expressa o recessivo → 1/4 = 25%.",
        "banca_intent": "Avaliar domínio da segregação mendeliana e cálculo de probabilidade genotípica.",
        "macete": "Aa x Aa → sempre 3:1 fenotípico e 1:2:1 genotípico em monohibridismo clássico.",
        "pegadinha": "Confundir probabilidade do heterozigoto (50%) com a do recessivo (25%).",
        "related_topics": ["Probabilidade", "Citologia"],
        "keywords": ["heterozigoto", "recessivo", "cruzamento"],
        "statement_verbs": ["é"],
    },
    {
        "id": "bio-2018-01",
        "year": 2018,
        "subject": "Biologia",
        "topic": "Genética",
        "subtopic": "Mendel",
        "statement": "Um casal apresenta fenótipo dominante para uma característica monogênica autossômica, porém já teve um filho com fenótipo recessivo. Considerando herança mendeliana clássica, o genótipo mais provável desse casal é:",
        "options": ["AA e AA", "AA e Aa", "Aa e Aa", "aa e aa", "AA e aa"],
        "correct_index": 2,
        "difficulty": "Média",
        "tags": ["mendel"],
        "syllabus_id": "bio-gen",
        "resolution": "1) Filho recessivo (aa) só nasce se receber alelo a de ambos os pais.\n2) Pais de fenótipo dominante não podem ser aa; logo precisam carregar a.\n3) Portanto ambos são heterozigotos Aa (não AA, que não doaria a).",
        "banca_intent": "Verificar se o aluno interpreta pedigree/família com recessivo nascido de pais dominantes.",
        "macete": "Filho recessivo + pais dominantes ⇒ ambos heterozigotos.",
        "pegadinha": "Marcar AA e Aa — impossível gerar aa.",
        "related_topics": ["Probabilidade"],
        "keywords": ["fenótipo", "genótipo", "recessivo"],
        "statement_verbs": ["é"],
    },
    {
        "id": "bio-2020-01",
        "year": 2020,
        "subject": "Biologia",
        "topic": "Genética",
        "subtopic": "Mendel",
        "statement": "No di-hibridismo mendeliano clássico com segregação independente, o cruzamento AaBb x AaBb (dois loci autossômicos, dominância completa em cada um) produz a proporção fenotípica esperada de:",
        "options": ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1", "9:7"],
        "correct_index": 0,
        "difficulty": "Difícil",
        "tags": ["di-hibridismo"],
        "syllabus_id": "bio-gen",
        "resolution": "1) Cada loco segrega 3:1 no fenótipo (A_ vs aa; B_ vs bb).\n2) Independência multiplica as razões: 9 A_B_ : 3 A_bb : 3 aaB_ : 1 aabb.\n3) Assim a proporção clássica é 9:3:3:1.",
        "banca_intent": "Cobrar independência de loci e proporção 9:3:3:1.",
        "macete": "Dois caracteres × segregação independente = 9:3:3:1.",
        "pegadinha": "Usar 3:1 (válido só para um gene).",
        "related_topics": ["Probabilidade"],
        "keywords": ["di-hibridismo", "proporção"],
        "statement_verbs": ["é"],
    },
    {
        "id": "bio-2022-01",
        "year": 2022,
        "subject": "Biologia",
        "topic": "Genética",
        "subtopic": "Mendel",
        "statement": "Em genética mendeliana, um teste cross cruza um indivíduo de fenótipo dominante com um recessivo (aa). Se a prole resultante apresenta cerca de 50% de recessivos, o genótipo do indivíduo testado é:",
        "options": ["AA", "Aa", "aa", "Impossível determinar", "AABB"],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["teste-cross"],
        "syllabus_id": "bio-gen",
        "resolution": "1) Teste cross: desconhecido × aa.\n2) Se o testado fosse AA, 100% da prole seria dominante (Aa).\n3) Com cerca de 50% recessivos, o testado deve ser heterozigoto Aa (Aa×aa → 1:1).",
        "banca_intent": "Avaliar compreensão de teste cross.",
        "macete": "50% recessivos no teste cross ⇒ heterozigoto.",
        "pegadinha": "Confundir com AA (que daria 0% recessivos).",
        "related_topics": ["Probabilidade"],
        "keywords": ["teste cross", "heterozigoto"],
        "statement_verbs": ["é"],
    },
    {
        "id": "bio-2025-01",
        "year": 2025,
        "subject": "Biologia",
        "topic": "Genética",
        "subtopic": "Mendel",
        "statement": "A segunda lei de Mendel (segregação independente) descreve a transmissão conjunta de dois genes. Essa lei aplica-se de modo clássico quando os genes envolvidos estão:",
        "options": [
            "No mesmo cromossomo e muito próximos",
            "Em cromossomos diferentes (ou longe o bastante)",
            "Apenas no cromossomo X",
            "Somente em genes letais",
            "Apenas em mitocôndrias",
        ],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["mendel", "ligação gênica"],
        "syllabus_id": "bio-gen",
        "resolution": "1) Genes no mesmo cromossomo e muito próximos tendem a herdar-se ligados.\n2) Segregação independente exige recombinação livre entre loci.\n3) Isso ocorre em cromossomos diferentes ou quando estão suficientemente afastados no mesmo cromossomo.",
        "banca_intent": "Distinguir segregação independente de ligação gênica.",
        "macete": "Genes 'longe' ou em cromossomos diferentes → independente.",
        "pegadinha": "Achar que qualquer dois genes segregam independente.",
        "related_topics": ["Citologia"],
        "keywords": ["segregação", "cromossomo"],
        "statement_verbs": ["aplica-se"],
    },
    {
        "id": "mat-2017-01",
        "year": 2017,
        "subject": "Matemática",
        "topic": "Geometria analítica",
        "subtopic": "Reta",
        "statement": "No plano cartesiano, a distância euclidiana entre os pontos A(1,2) e B(4,6) é um número real positivo. Calculando pela fórmula da distância entre dois pontos, o valor obtido é:",
        "options": ["3", "4", "5", "6", "7"],
        "correct_index": 2,
        "difficulty": "Fácil",
        "tags": ["distância"],
        "syllabus_id": "mat-geo",
        "resolution": "1) Use d = √[(x2−x1)² + (y2−y1)²].\n2) Substitui: √[(4−1)² + (6−2)²] = √(9+16).\n3) √25 = 5.",
        "banca_intent": "Aplicar fórmula da distância entre dois pontos.",
        "macete": "Pitágoras no plano: catetos Δx e Δy.",
        "pegadinha": "Somar Δx+Δy em vez da hipotenusa.",
        "related_topics": ["Funções"],
        "keywords": ["distância", "pontos"],
        "statement_verbs": ["é"],
    },
    {
        "id": "mat-2019-01",
        "year": 2019,
        "subject": "Matemática",
        "topic": "Geometria analítica",
        "subtopic": "Reta",
        "statement": "Determine a equação reduzida da reta que passa pelos pontos (0,1) e (2,5) no plano cartesiano, escrevendo-a na forma y = mx + b com coeficiente angular e linear corretos:",
        "options": ["y = 2x + 1", "y = x + 1", "y = 2x - 1", "y = 3x + 1", "y = 2x"],
        "correct_index": 0,
        "difficulty": "Média",
        "tags": ["reta"],
        "syllabus_id": "mat-geo",
        "resolution": "1) Coeficiente angular m = (5−1)/(2−0) = 4/2 = 2.\n2) Em x=0 a ordenada é 1 ⇒ intercepto b=1.\n3) Logo y = 2x + 1.",
        "banca_intent": "Determinar equação reduzida da reta.",
        "macete": "m = Δy/Δx; depois use um ponto.",
        "pegadinha": "Inverter Δx/Δy no coeficiente angular.",
        "related_topics": ["Funções"],
        "keywords": ["reta", "coeficiente angular"],
        "statement_verbs": ["é"],
    },
    {
        "id": "mat-2021-01",
        "year": 2021,
        "subject": "Matemática",
        "topic": "Geometria analítica",
        "subtopic": "Circunferência",
        "statement": "A circunferência com centro na origem (0,0) e raio igual a 3 unidades tem equação cartesiana canônica. Assinale a alternativa que representa corretamente essa circunferência:",
        "options": ["x² + y² = 3", "x² + y² = 9", "x + y = 9", "x² - y² = 9", "(x-3)² + y² = 0"],
        "correct_index": 1,
        "difficulty": "Fácil",
        "tags": ["circunferência"],
        "syllabus_id": "mat-geo",
        "resolution": "1) Forma canônica com centro (0,0): x² + y² = r².\n2) Raio r = 3 ⇒ r² = 9.\n3) Portanto x² + y² = 9 (não =3).",
        "banca_intent": "Reconhecer equação canônica da circunferência.",
        "macete": "Raio ao quadrado no segundo membro.",
        "pegadinha": "Escrever = r e não = r².",
        "related_topics": ["Funções"],
        "keywords": ["circunferência", "raio"],
        "statement_verbs": ["tem"],
    },
    {
        "id": "mat-2023-01",
        "year": 2023,
        "subject": "Matemática",
        "topic": "Geometria analítica",
        "subtopic": "Reta",
        "statement": "Duas retas não verticais no plano cartesiano são perpendiculares entre si. Relacionando seus coeficientes angulares m1 e m2, a condição algébrica necessária e suficiente é:",
        "options": ["m1 = m2", "m1 + m2 = 0", "m1 · m2 = -1", "m1 · m2 = 1", "m1 / m2 = -1"],
        "correct_index": 2,
        "difficulty": "Média",
        "tags": ["perpendicular"],
        "syllabus_id": "mat-geo",
        "resolution": "1) Retas paralelas: m1 = m2; perpendiculares envolvem produto.\n2) O ângulo de 90° implica m2 = −1/m1 (m1≠0).\n3) Equivalentemente: m1 · m2 = −1.",
        "banca_intent": "Cobrar condição de perpendicularidade.",
        "macete": "Perpendicular ⇒ produto dos ângulos = -1.",
        "pegadinha": "Confundir com paralelas (m1=m2).",
        "related_topics": ["Funções"],
        "keywords": ["perpendicular", "coeficiente"],
        "statement_verbs": ["têm"],
    },
    {
        "id": "mat-2025-01",
        "year": 2025,
        "subject": "Matemática",
        "topic": "Geometria analítica",
        "subtopic": "Reta",
        "statement": "Considere o segmento de reta cujos extremos são os pontos (2,4) e (6,10) no plano. O ponto médio desse segmento, obtido pela média aritmética das coordenadas, é:",
        "options": ["(4,7)", "(4,6)", "(3,7)", "(8,14)", "(2,5)"],
        "correct_index": 0,
        "difficulty": "Fácil",
        "tags": ["ponto médio"],
        "syllabus_id": "mat-geo",
        "resolution": "1) Fórmula: M = ((x1+x2)/2, (y1+y2)/2).\n2) Abscissa: (2+6)/2 = 4; ordenada: (4+10)/2 = 7.\n3) Ponto médio = (4,7).",
        "banca_intent": "Calcular ponto médio.",
        "macete": "Média aritmética das coordenadas.",
        "pegadinha": "Somar sem dividir por 2.",
        "related_topics": ["Funções"],
        "keywords": ["ponto médio"],
        "statement_verbs": ["é"],
    },
    {
        "id": "mat-fun-2018",
        "year": 2018,
        "subject": "Matemática",
        "topic": "Funções",
        "subtopic": "Exponencial",
        "statement": "Seja a função exponencial f definida por f(x) = 2^x, com domínio nos reais. Avaliando a função no ponto x = 3, o valor numérico de f(3) é igual a:",
        "options": ["3", "5", "6", "8", "9"],
        "correct_index": 3,
        "difficulty": "Fácil",
        "tags": ["exponencial"],
        "syllabus_id": "mat-fun",
        "resolution": "1) Por definição, f(3) = 2^3.\n2) 2^3 = 2·2·2.\n3) Resultado: 8.",
        "banca_intent": "Avaliar cálculo direto de função exponencial.",
        "macete": "aⁿ = a multiplicado n vezes.",
        "pegadinha": "Fazer 2·3=6.",
        "related_topics": ["Probabilidade"],
        "keywords": ["exponencial"],
        "statement_verbs": ["é"],
    },
    {
        "id": "mat-fun-2024",
        "year": 2024,
        "subject": "Matemática",
        "topic": "Funções",
        "subtopic": "Exponencial",
        "statement": "Considere a função real f(x) = 2^x, com base maior do que 1. Do ponto de vista do crescimento ou decrescimento em todo o domínio real, essa função é corretamente classificada como:",
        "options": ["Decrescente", "Constante", "Crescente", "Periódica", "Linear"],
        "correct_index": 2,
        "difficulty": "Fácil",
        "tags": ["exponencial"],
        "syllabus_id": "mat-fun",
        "resolution": "1) Em f(x)=a^x, se a>1 a função é crescente.\n2) Aqui a=2>1; se x1<x2 então 2^{x1}<2^{x2}.\n3) Logo f é crescente (não periódica nem linear).",
        "banca_intent": "Classificar monotonia de exponencial.",
        "macete": "Base > 1 cresce; 0<base<1 decresce.",
        "pegadinha": "Confundir com logaritmo.",
        "related_topics": ["Geometria analítica"],
        "keywords": ["crescente"],
        "statement_verbs": ["é"],
    },
    {
        "id": "qui-2017-01",
        "year": 2017,
        "subject": "Química",
        "topic": "Estequiometria",
        "subtopic": "Mol",
        "statement": "Sabendo que a massa molar da água (H2O) é aproximadamente 18 g/mol, a quantidade de matéria correspondente a uma amostra de 18 g de H2O pura, em mols, é:",
        "options": ["0,5 mol", "1 mol", "2 mol", "18 mol", "36 mol"],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["mol"],
        "syllabus_id": "qui-est",
        "resolution": "1) n = m / M.\n2) m=18 g e M≈18 g/mol.\n3) n = 18/18 = 1 mol.",
        "banca_intent": "Relacionar massa e mol.",
        "macete": "n = m/M.",
        "pegadinha": "Usar massa atômica só do oxigênio.",
        "related_topics": ["Química orgânica"],
        "keywords": ["mol", "água"],
        "statement_verbs": ["é"],
    },
    {
        "id": "qui-2021-01",
        "year": 2021,
        "subject": "Química",
        "topic": "Estequiometria",
        "subtopic": "Mol",
        "statement": "Na molécula de dióxido de carbono (CO2) há dois átomos de oxigênio por fórmula. Considerando 2 mol de CO2, a quantidade de matéria de átomos de oxigênio presentes é:",
        "options": ["1", "2", "3", "4", "6"],
        "correct_index": 3,
        "difficulty": "Média",
        "tags": ["mol"],
        "syllabus_id": "qui-est",
        "resolution": "1) Cada mol de CO2 contém 2 mol de átomos de O.\n2) Em 2 mol de CO2: 2 × 2 = 4 mol de O.\n3) Resposta: 4 mols de átomos de oxigênio.",
        "banca_intent": "Contar átomos via estequiometria.",
        "macete": "Multiplique mols da fórmula pelos índices.",
        "pegadinha": "Contar moléculas em vez de átomos de O.",
        "related_topics": ["Química orgânica"],
        "keywords": ["oxigênio", "CO2"],
        "statement_verbs": ["há"],
    },
    {
        "id": "pt-2017-01",
        "year": 2017,
        "subject": "Língua Portuguesa e Literatura",
        "topic": "Interpretação de texto",
        "subtopic": "Funções da linguagem",
        "statement": "Em questões de interpretação, quando o enunciado pede o objetivo do texto ou a intenção comunicativa dominante, o leitor deve priorizar a identificação da:",
        "options": [
            "Função predominante da linguagem",
            "Figura de linguagem mais rara",
            "Ortografia do título",
            "Métrica do verso",
            "Classe gramatical do sujeito",
        ],
        "correct_index": 0,
        "difficulty": "Média",
        "tags": ["funções da linguagem"],
        "syllabus_id": "pt-int",
        "resolution": "1) Objetivo do texto amarra-se à função da linguagem predominante.\n2) Outros elementos (figura rara, ortografia) são secundários para essa pergunta.\n3) Logo, priorize a função predominante (referencial, apelativa, emotiva etc.).",
        "banca_intent": "Avaliar se o aluno distingue denotação/conotação e função predominante.",
        "macete": "Apareceu 'objetivo do texto' ⇒ procure a função predominante.",
        "pegadinha": "Trocar coesão por coerência ou focar só em gramática.",
        "related_topics": ["Coesão e coerência", "Literatura"],
        "keywords": ["objetivo", "função", "texto"],
        "statement_verbs": ["deve"],
    },
    {
        "id": "pt-2018-01",
        "year": 2018,
        "subject": "Língua Portuguesa e Literatura",
        "topic": "Interpretação de texto",
        "subtopic": "Funções da linguagem",
        "statement": "Segundo o modelo de Jakobson, a função apelativa (também chamada conativa) organiza o discurso de modo a influenciar o interlocutor. Essa função centra-se principalmente no:",
        "options": ["Emissor", "Receptor", "Canal", "Código", "Contexto"],
        "correct_index": 1,
        "difficulty": "Fácil",
        "tags": ["funções da linguagem"],
        "syllabus_id": "pt-int",
        "resolution": "1) Função emotiva → emissor; referencial → contexto.\n2) Apelativa/conativa busca persuadir, ordenar ou aconselhar.\n3) Seu foco é o receptor (leitor/ouvinte).",
        "banca_intent": "Identificar foco da função conativa.",
        "macete": "Apelativa = chama o tu/você.",
        "pegadinha": "Associar apelativa ao emissor (expressiva).",
        "related_topics": ["Coesão e coerência"],
        "keywords": ["apelativa", "receptor"],
        "statement_verbs": ["centra-se"],
    },
    {
        "id": "pt-2020-01",
        "year": 2020,
        "subject": "Língua Portuguesa e Literatura",
        "topic": "Coesão e coerência",
        "subtopic": "Conectivos",
        "statement": "Na coesão textual, conectivos estabelecem relações lógicas entre orações. O conectivo portanto, empregado tipicamente em argumentação, indica relação de:",
        "options": ["Oposição", "Conclusão", "Adição", "Alternância", "Tempo"],
        "correct_index": 1,
        "difficulty": "Fácil",
        "tags": ["conectivos"],
        "syllabus_id": "pt-coe",
        "resolution": "1) Mas/porém marcam oposição; e marca adição.\n2) Portanto/logo/assim introduzem conclusão decorrente.\n3) Logo, portanto indica conclusão (ou consequência lógica).",
        "banca_intent": "Classificar conectivos de conclusão.",
        "macete": "Portanto/logo/pois (posposto) ⇒ conclusão.",
        "pegadinha": "A banca troca coesão (amarração) por coerência (sentido global).",
        "related_topics": ["Interpretação de texto"],
        "keywords": ["portanto", "conclusão"],
        "statement_verbs": ["indica"],
    },
    {
        "id": "pt-2022-01",
        "year": 2022,
        "subject": "Língua Portuguesa e Literatura",
        "topic": "Interpretação de texto",
        "subtopic": "Funções da linguagem",
        "statement": "Nos estudos de semântica lexical, denotação e conotação descrevem modos distintos de significação. Denotação e conotação diferem porque a denotação:",
        "options": [
            "É o sentido figurado",
            "É o sentido literal/objetivo",
            "Independe do contexto sempre",
            "Só ocorre em poemas",
            "É sinônimo de ironia",
        ],
        "correct_index": 1,
        "difficulty": "Fácil",
        "tags": ["denotação"],
        "syllabus_id": "pt-int",
        "resolution": "1) Conotação explora sentido figurado, subjetivo ou contextual.\n2) Denotação corresponde ao sentido literal, de dicionário.\n3) Portanto a denotação é o sentido literal/objetivo.",
        "banca_intent": "Distinguir denotação de conotação.",
        "macete": "D de dicionário = denotação.",
        "pegadinha": "Inverter os conceitos.",
        "related_topics": ["Literatura", "Coesão e coerência"],
        "keywords": ["denotação", "conotação"],
        "statement_verbs": ["diferem"],
    },
    {
        "id": "pt-2025-01",
        "year": 2025,
        "subject": "Língua Portuguesa e Literatura",
        "topic": "Literatura",
        "subtopic": "Escolas literárias",
        "statement": "No Romantismo brasileiro do século XIX, sobretudo nas primeiras gerações, a produção literária valoriza especialmente, como traço estético e ideológico recorrente:",
        "options": [
            "O objetivismo científico",
            "O nacionalismo e a natureza idealizada",
            "A métrica perfeita parnasiana apenas",
            "O concretismo tipográfico",
            "O teatro do absurdo",
        ],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["romantismo"],
        "syllabus_id": "pt-lit",
        "resolution": "1) Parnasianismo enfatiza forma e objetividade; Romantismo, subjetividade.\n2) No Brasil, destaca-se o indianismo e a natureza idealizada.\n3) Assim, valoriza nacionalismo e natureza idealizada.",
        "banca_intent": "Reconhecer marcas do Romantismo.",
        "macete": "Romantismo BR = pátria + sentimento + natureza.",
        "pegadinha": "Misturar com Parnasianismo (forma/arte pela arte).",
        "related_topics": ["Interpretação de texto"],
        "keywords": ["romantismo", "nacionalismo"],
        "statement_verbs": ["valoriza"],
    },
    {
        "id": "fis-2019-01",
        "year": 2019,
        "subject": "Física",
        "topic": "Cinemática",
        "subtopic": "MRUV",
        "statement": "Um móvel em movimento retilíneo uniformemente variado parte do repouso com aceleração constante de 2 m/s². Após 4 segundos de movimento, sua velocidade escalar é:",
        "options": ["2 m/s", "4 m/s", "6 m/s", "8 m/s", "16 m/s"],
        "correct_index": 3,
        "difficulty": "Fácil",
        "tags": ["MRUV"],
        "syllabus_id": "fis-cin",
        "resolution": "1) Equação: v = v0 + a·t.\n2) v0=0, a=2 m/s², t=4 s.\n3) v = 0 + 2·4 = 8 m/s.",
        "banca_intent": "Aplicar equação horária da velocidade no MRUV.",
        "macete": "Partiu do repouso ⇒ v = a t.",
        "pegadinha": "Usar s = a t sem o ½.",
        "related_topics": ["Eletrodinâmica"],
        "keywords": ["aceleração", "velocidade"],
        "statement_verbs": ["é"],
    },
    {
        "id": "fis-2024-01",
        "year": 2024,
        "subject": "Física",
        "topic": "Eletrodinâmica",
        "subtopic": "Circuitos",
        "statement": "Em um resistor ôhmico ideal, a corrente e a tensão relacionam-se por U = R·I. Se a tensão aplicada dobra e a resistência permanece constante, o que ocorre com a corrente elétrica?",
        "options": ["Cai à metade", "Permanece igual", "Dobra", "Quadruplica", "Zera"],
        "correct_index": 2,
        "difficulty": "Fácil",
        "tags": ["Ohm"],
        "syllabus_id": "fis-ele",
        "resolution": "1) De U=R·I obtém-se I=U/R.\n2) R constante e U → 2U implica I → 2I.\n3) Portanto a corrente dobra.",
        "banca_intent": "Aplicar lei de Ohm.",
        "macete": "I proporcional a U se R fixo.",
        "pegadinha": "Pensar que potência em vez de corrente.",
        "related_topics": ["Cinemática"],
        "keywords": ["Ohm", "corrente"],
        "statement_verbs": ["permanece", "dobra"],
    },
    {
        "id": "geo-2020-01",
        "year": 2020,
        "subject": "Geografia",
        "topic": "Geografia do Brasil",
        "subtopic": "Nordeste",
        "statement": "O domínio semiárido do Nordeste brasileiro apresenta características climáticas e hidrológicas específicas. Esse domínio é marcado principalmente por:",
        "options": [
            "Chuvas bem distribuídas o ano todo",
            "Irregularidade pluviométrica e longas estiagens",
            "Clima equatorial úmido permanente",
            "Tundra costeira",
            "Glaciação atual",
        ],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["nordeste", "semiárido"],
        "syllabus_id": "geo-br",
        "resolution": "1) Clima equatorial úmido não descreve o semiárido nordestino.\n2) Há forte irregularidade das chuvas e estiagens prolongadas.\n3) Marca principal: irregularidade pluviométrica e longas estiagens.",
        "banca_intent": "Caracterizar o semiárido nordestino.",
        "macete": "Semiárido ≠ ausência total de chuva; é irregularidade.",
        "pegadinha": "Associar Nordeste só a 'deserto absoluto'.",
        "related_topics": ["Brasil República"],
        "keywords": ["semiárido", "estiagem"],
        "statement_verbs": ["é"],
    },
    {
        "id": "his-2018-01",
        "year": 2018,
        "subject": "História",
        "topic": "Brasil República",
        "subtopic": "Século XX",
        "statement": "A Era Vargas (1930–1945) reorganizou o Estado brasileiro após a crise da República Oligárquica. Esse período caracterizou-se, entre outros aspectos, por:",
        "options": [
            "Ausência total de interventores",
            "Centralização política e trabalhismo estatal",
            "Fim imediato da indústria nacional",
            "Retorno ao império",
            "Adoção do parlamentarismo inglês sem mudanças",
        ],
        "correct_index": 1,
        "difficulty": "Média",
        "tags": ["Vargas"],
        "syllabus_id": "his-br",
        "resolution": "1) Houve interventores estaduais e fortalecimento do Executivo.\n2) Avançou a legislação trabalhista e o trabalhismo estatal.\n3) Sintetizando: centralização política e trabalhismo estatal.",
        "banca_intent": "Identificar traços da Era Vargas.",
        "macete": "Vargas = Estado forte + leis trabalhistas.",
        "pegadinha": "Reduzir Vargas só ao Estado Novo (1937-45).",
        "related_topics": ["Cultura e sociedade"],
        "keywords": ["Vargas", "trabalhismo"],
        "statement_verbs": ["caracterizou-se"],
    },
    {
        "id": "bio-eco-2019",
        "year": 2019,
        "subject": "Biologia",
        "topic": "Ecologia",
        "subtopic": "Cadeias alimentares",
        "statement": "Em ecologia de cadeias e teias alimentares, os organismos autótrofos que produzem matéria orgânica a partir de energia luminosa ou química ocupam qual posição na estrutura trófica?",
        "options": ["Decompositores", "Consumidores primários", "Primeiro nível trófico", "Topo de cadeia", "Parasitas obrigatórios"],
        "correct_index": 2,
        "difficulty": "Fácil",
        "tags": ["ecologia"],
        "syllabus_id": "bio-eco",
        "resolution": "1) Consumidores primários alimentam-se de produtores.\n2) Produtores (autótrofos) iniciam o fluxo de energia.\n3) Eles ocupam o primeiro nível trófico.",
        "banca_intent": "Identificar níveis tróficos.",
        "macete": "Quem produz matéria orgânica = base da cadeia.",
        "pegadinha": "Colocar produtores como consumidores.",
        "related_topics": ["Fisiologia humana"],
        "keywords": ["produtores", "nível trófico"],
        "statement_verbs": ["ocupam"],
    },
    {
        "id": "bio-cit-2023",
        "year": 2023,
        "subject": "Biologia",
        "topic": "Citologia",
        "subtopic": "Membrana",
        "statement": "A membrana plasmática de células eucarióticas é composta por bicamada lipídica com proteínas associadas em movimento lateral. O modelo que descreve essa organização dinâmica é o de:",
        "options": ["Dupla hélice rígida", "Mosaico fluido", "Parede celular única", "Capsídeo viral", "Esporulação"],
        "correct_index": 1,
        "difficulty": "Fácil",
        "tags": ["membrana"],
        "syllabus_id": "bio-cit",
        "resolution": "1) Dupla hélice refere-se ao DNA, não à membrana.\n2) Singer e Nicolson propuseram o mosaico fluido.\n3) Resposta: modelo do mosaico fluido.",
        "banca_intent": "Reconhecer estrutura da membrana.",
        "macete": "Fosfolipídios + proteínas 'flutuando' = mosaico fluido.",
        "pegadinha": "Confundir com parede celular vegetal.",
        "related_topics": ["Fisiologia humana"],
        "keywords": ["mosaico fluido"],
        "statement_verbs": ["é"],
    },
]


def seed(force: bool = False) -> dict[str, int]:
    init_db()
    with db() as conn:
        count_q = conn.execute("SELECT COUNT(*) AS c FROM questions").fetchone()["c"]
        if count_q > 40 and not force:
            return {"syllabus": conn.execute("SELECT COUNT(*) AS c FROM syllabus").fetchone()["c"], "questions": count_q, "skipped": 1}

        # Ciclo K: preservar oficiais UEMA_PAES / ingest ao forçar reseed de treino
        preserved: list[dict[str, Any]] = []
        if force:
            try:
                preserved = [
                    dict(r)
                    for r in conn.execute(
                        """
                        SELECT * FROM questions
                        WHERE UPPER(COALESCE(exam_board,'')) = 'UEMA_PAES'
                           OR (
                             COALESCE(generated,0)=0
                             AND (
                               LOWER(COALESCE(source,'')) LIKE '%pdf%'
                               OR LOWER(COALESCE(source,'')) LIKE '%oficial%'
                               OR LOWER(COALESCE(source,'')) LIKE '%ingest%'
                             )
                           )
                        """
                    ).fetchall()
                ]
            except Exception:
                preserved = []
            conn.execute("PRAGMA foreign_keys = OFF")
            for table in (
                "answers",
                "revisions",
                "flashcards",
                "embeddings",
                "study_plan",
                "questions",
                "syllabus",
            ):
                try:
                    conn.execute(f"DELETE FROM {table}")
                except Exception:
                    pass
            conn.execute("PRAGMA foreign_keys = ON")

        syllabus_all = {s["id"]: s for s in SYLLABUS}
        for s in EXTRA_SYLLABUS:
            syllabus_all[s["id"]] = s

        for item in syllabus_all.values():
            conn.execute(
                """
                INSERT OR REPLACE INTO syllabus (id, subject, topic, subtopic, weight)
                VALUES (?, ?, ?, ?, ?)
                """,
                (item["id"], item["subject"], item["topic"], item.get("subtopic"), item.get("weight", 1.0)),
            )

        all_questions = list(QUESTIONS) + build_extra_questions()
        for q in all_questions:
            conn.execute(
                """
                INSERT OR REPLACE INTO questions (
                    id, year, subject, topic, subtopic, statement, options_json, correct_index,
                    difficulty, tags_json, syllabus_id, source, resolution, banca_intent,
                    macete, pegadinha, related_topics_json, keywords_json, statement_verbs_json,
                    avg_text_len, generated, exam_board, similarity_of, similarity_note
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?)
                """,
                (
                    q["id"],
                    q["year"],
                    q["subject"],
                    q["topic"],
                    q.get("subtopic"),
                    q["statement"],
                    json.dumps(q["options"], ensure_ascii=False),
                    q["correct_index"],
                    q["difficulty"],
                    json.dumps(q.get("tags", []), ensure_ascii=False),
                    q.get("syllabus_id"),
                    "treino_padrao_paes",
                    q.get("resolution"),
                    q.get("banca_intent"),
                    q.get("macete"),
                    q.get("pegadinha"),
                    json.dumps(q.get("related_topics", []), ensure_ascii=False),
                    json.dumps(q.get("keywords", []), ensure_ascii=False),
                    json.dumps(q.get("statement_verbs", []), ensure_ascii=False),
                    len(q["statement"]),
                    q.get("exam_board", "TREINO"),
                    q.get("similarity_of"),
                    q.get("similarity_note"),
                ),
            )

        restored = 0
        for row in preserved:
            cols = [
                "id", "year", "subject", "topic", "subtopic", "statement", "options_json", "correct_index",
                "difficulty", "tags_json", "syllabus_id", "source", "resolution", "banca_intent",
                "macete", "pegadinha", "related_topics_json", "keywords_json", "statement_verbs_json",
                "has_graph", "has_table", "has_image", "avg_text_len", "generated", "approved",
                "exam_board", "similarity_of", "similarity_note",
            ]
            present = [c for c in cols if c in row]
            placeholders = ", ".join("?" for _ in present)
            conn.execute(
                f"INSERT OR REPLACE INTO questions ({', '.join(present)}) VALUES ({placeholders})",
                [row[c] for c in present],
            )
            restored += 1

        # Tema de redação inicial
        existing = conn.execute("SELECT value FROM settings WHERE key='essay_themes'").fetchone()
        if not existing:
            themes = [
                "Desafios da saúde pública no Maranhão",
                "O acesso à universidade pública e a meritocracia",
                "Tecnologia e ética na formação médica",
            ]
            conn.execute(
                "INSERT INTO settings (key, value) VALUES (?, ?)",
                ("essay_themes", json.dumps(themes, ensure_ascii=False)),
            )

        conn.commit()
        return {
            "syllabus": len(syllabus_all),
            "questions": len(all_questions) + restored,
            "treino": len(all_questions),
            "preservedOfficial": restored,
            "skipped": 0,
        }


if __name__ == "__main__":
    print(seed(force=True))
