"""Questões de treino DENSAS (ciclo I) — originais, sem clones rasos.

Fonte: treino_padrao_paes. Anos são rótulos de organização, NÃO provas oficiais.
"""

from __future__ import annotations

from typing import Any

EXTRA_SYLLABUS: list[dict[str, Any]] = []


def _q(
    i: int,
    year: int,
    subject: str,
    topic: str,
    subtopic: str,
    statement: str,
    options: list[str],
    correct: int,
    difficulty: str,
    syllabus_id: str,
    resolution: str,
    banca: str,
    macete: str,
    pegadinha: str,
    related: list[str],
    keywords: list[str],
) -> dict[str, Any]:
    return {
        "id": f"treino-denso-{i:03d}",
        "year": year,
        "subject": subject,
        "topic": topic,
        "subtopic": subtopic,
        "statement": statement,
        "options": options,
        "correct_index": correct,
        "difficulty": difficulty,
        "tags": keywords[:3],
        "syllabus_id": syllabus_id,
        "resolution": resolution,
        "banca_intent": banca,
        "macete": macete,
        "pegadinha": pegadinha,
        "related_topics": related,
        "keywords": keywords,
        "statement_verbs": ["é", "assinale", "indique"][:1],
        "exam_board": "TREINO",
        "similarity_of": None,
        "similarity_note": None,
    }


def build_extra_questions() -> list[dict[str, Any]]:
    """~35 itens densos; somados ao núcleo de seed.py ficam ~55–60 questões."""
    raw: list[tuple] = [
        (
            2018,
            "Biologia",
            "Genética",
            "Mendel",
            "bio-gen",
            "Um casal de fenótipo dominante para uma característica autossômica monogênica já teve um filho com fenótipo recessivo. Sabendo-se que ambos os pais são heterozigotos (herança mendeliana clássica), a probabilidade de o próximo filho também ser recessivo é:",
            ["1/2", "1/4", "1/8", "2/3", "3/4"],
            1,
            "Média",
            "1) Filho recessivo confirma alelo recessivo nos dois pais.\n2) Pais dominantes + aa ⇒ Aa × Aa.\n3) Em Aa × Aa, P(aa)=1/4; gestações são independentes.",
            "Cobrar independência entre gestações e segregação 1:2:1.",
            "Cada filho: Aa×Aa → 25% recessivo; irmãos não mudam a próxima probabilidade.",
            "Usar 2/3 (condicional) quando a questão já fixou genótipos dos pais.",
            ["Probabilidade", "Citologia"],
            ["mendel", "heterozigoto", "recessivo"],
        ),
        (
            2019,
            "Biologia",
            "Genética",
            "Mendel",
            "bio-gen",
            "Em um heredograma, um casal sem a doença (fenótipo normal) tem duas filhas afetadas e um filho normal. A doença é rara, autossômica e recessiva. A interpretação mais consistente é:",
            [
                "Doença ligada ao Y",
                "Doença dominante com penetrância completa",
                "Ambos os pais são obrigatoriamente heterozigotos portadores",
                "Apenas a mãe é portadora",
                "Mutação de novo em todas as filhas",
            ],
            2,
            "Difícil",
            "1) Pais não afetados + filhos afetados ⇒ recessivo.\n2) Ambos os sexos afetados reforçam padrão autossômico.\n3) Pais normais que geram afetados devem ser Aa.",
            "Ler heredograma sem inventar ligação sexual sem evidência.",
            "Pais normais + filhos afetados = recessivo; ambos portadores.",
            "Assumir dominante incompleta sem dados de penetrância.",
            ["Probabilidade"],
            ["heredograma", "recessivo", "portador"],
        ),
        (
            2020,
            "Biologia",
            "Citologia",
            "Membrana",
            "bio-cit",
            "No modelo do mosaico fluido, o transporte de íons Na+ contra o gradiente eletroquímico com gasto direto de ATP caracteriza principalmente:",
            [
                "Difusão simples",
                "Osmose",
                "Transporte passivo por canais",
                "Bomba ativa (transporte ativo primário)",
                "Endocitose de fase fluida",
            ],
            3,
            "Média",
            "1) Contra o gradiente + ATP = transporte ativo.\n2) Bomba Na+/K+ é o exemplo clássico de ativo primário.\n3) Canais e difusão são passivos.",
            "Diferenciar passivo vs ativo e primário vs secundário.",
            "Contra gradiente + ATP ⇒ bomba/ativo.",
            "Marcar canal iônico só porque envolve íon.",
            ["Fisiologia humana"],
            ["membrana", "ATP", "bomba"],
        ),
        (
            2021,
            "Biologia",
            "Ecologia",
            "Cadeias alimentares",
            "bio-eco",
            "Se produtores capturam E unidades de energia útil e a eficiência de transferência é cerca de 10% por nível, a ordem de grandeza esperada no terceiro nível trófico (consumidor secundário) é:",
            ["E", "0,1 E", "0,01 E", "0,001 E", "10 E"],
            2,
            "Média",
            "1) Produtores: E.\n2) Herbívoros: ~0,1 E.\n3) Consumidor secundário: ~0,01 E.",
            "Aplicar a regra dos 10% sem confundir níveis.",
            "Cada nível divide por ~10; dois saltos ⇒ /100.",
            "Errar a contagem do nível trófico.",
            ["Fisiologia humana"],
            ["piramide", "energia", "trofico"],
        ),
        (
            2022,
            "Biologia",
            "Fisiologia humana",
            "Sistemas",
            "bio-fisio",
            "No exercício intenso, o aumento de CO2 e ácidos metabólicos desafia o pH sanguíneo. Qual mecanismo contribui de forma imediata para tamponar o sangue arterial?",
            [
                "Síntese de novas hemácias na medula",
                "Sistema tampão bicarbonato/ácido carbônico",
                "Digestão gástrica de proteínas",
                "Filtração glomerular de glicose",
                "Produção de bile",
            ],
            1,
            "Média",
            "1) CO2 + H2O ⇌ H2CO3 ⇌ H+ + HCO3−.\n2) HCO3−/H2CO3 é o principal tampão extracelular imediato.\n3) Ajustes respiratório/renal vêm depois; eritropoiese não é imediata.",
            "Relacionar exercício, CO2 e tampões.",
            "Tampão bicarbonato = resposta química rápida do plasma.",
            "Escolher rim/medula por associação com sangue.",
            ["Citologia", "Química"],
            ["ph", "bicarbonato", "homeostase"],
        ),
        (
            2019,
            "Matemática",
            "Funções",
            "Exponencial",
            "mat-fun",
            "A função f(x)=2^x modela o dobro de uma cultura a cada unidade de tempo. Se em t=0 há 500 indivíduos, o menor t inteiro em que a população ultrapassa 8000 é:",
            ["t=3", "t=4", "t=5", "t=6", "t=8"],
            2,
            "Média",
            "1) P(t)=500·2^t.\n2) 500·2^t > 8000 ⇒ 2^t > 16 ⇒ t > 4.\n3) Menor inteiro: t=5.",
            "Resolver inequação exponencial com base 2.",
            "Divida a meta pela inicial e conte potências de 2.",
            "Usar t=4 (igual a 8000) quando a pergunta pede ultrapassar.",
            ["Probabilidade"],
            ["exponencial", "dobramento"],
        ),
        (
            2020,
            "Matemática",
            "Funções",
            "Exponencial",
            "mat-fun",
            "Seja a função exponencial f(x)=a·b^x com parâmetros a>0 e 0<b<1. Analisando o comportamento para todo x real, qual afirmação é necessariamente verdadeira?",
            ["f é crescente", "f é constante", "f é decrescente", "f tem máximo em x=1", "f é periódica"],
            2,
            "Fácil",
            "1) 0<b<1 ⇒ cada incremento multiplica por fator <1.\n2) Logo f decresce.\n3) Sem periodicidade nem máximo privilegiado em x=1.",
            "Ler parâmetros da exponencial.",
            "Base entre 0 e 1 ⇒ decrescente.",
            "Confundir com b>1.",
            ["Geometria analítica"],
            ["exponencial", "decrescente"],
        ),
        (
            2021,
            "Matemática",
            "Geometria analítica",
            "Reta e circunferência",
            "mat-geo",
            "Considere a reta r: y=2x+1 e a circunferência C: (x-1)^2+(y-3)^2=10 no plano cartesiano. O número de pontos de interseção entre r e C é:",
            ["0", "1", "2", "3", "infinitos"],
            2,
            "Difícil",
            "1) Substitua y=2x+1 em C.\n2) (x-1)^2+(2x-2)^2=10 ⇒ 5(x-1)^2=10 ⇒ (x-1)^2=2.\n3) Duas soluções reais ⇒ duas interseções.",
            "Resolver sistema reta-circunferência.",
            "Quadrado positivo ⇒ 2 pontos.",
            "Assumir tangência sem calcular.",
            ["Funções"],
            ["reta", "circunferencia", "sistema"],
        ),
        (
            2018,
            "Matemática",
            "Probabilidade",
            "Eventos",
            "mat-prob",
            "Uma urna tem 4 bolas vermelhas e 6 azuis. Retiram-se 2 bolas sem reposição. A probabilidade de as duas serem vermelhas é:",
            ["2/15", "4/25", "1/5", "2/9", "4/45"],
            0,
            "Média",
            "1) P(1ª V)=4/10.\n2) P(2ª V|1ª V)=3/9.\n3) (4/10)*(3/9)=12/90=2/15.",
            "Probabilidade composta sem reposição.",
            "Multiplique sequencialmente e simplifique.",
            "Usar com reposição (4/10)^2.",
            ["Funções"],
            ["combinatoria", "urna"],
        ),
        (
            2022,
            "Matemática",
            "Probabilidade",
            "Eventos",
            "mat-prob",
            "Em um espaço amostral finito, os eventos A e B satisfazem P(A)=0,4, P(B)=0,5 e P(A∩B)=0,2. Aplicando a regra da união, o valor de P(A∪B) é:",
            ["0,5", "0,6", "0,7", "0,9", "1,0"],
            2,
            "Fácil",
            "1) P(A∪B)=P(A)+P(B)-P(A∩B).\n2) 0,4+0,5-0,2=0,7.\n3) Não são disjuntos.",
            "Fórmula da união.",
            "Soma menos interseção.",
            "Somar sem subtrair a interseção.",
            ["Funções"],
            ["uniao", "intersecao"],
        ),
        (
            2019,
            "Química",
            "Estequiometria",
            "Mol",
            "qui-est",
            "Na reação 2 H2 + O2 → 2 H2O, com 4 mol de H2 e 3 mol de O2 e rendimento total, a quantidade máxima de água (mol) e o reagente em excesso são:",
            [
                "4 mol de H2O; H2 em excesso",
                "4 mol de H2O; O2 em excesso",
                "3 mol de H2O; H2 em excesso",
                "6 mol de H2O; O2 em excesso",
                "2 mol de H2O; nenhum excesso",
            ],
            1,
            "Média",
            "1) 4 mol H2 produzem 4 mol H2O e consomem 2 mol O2.\n2) Sobram 1 mol O2.\n3) Logo 4 mol H2O e O2 em excesso.",
            "Identificar limitante pela razão estequiométrica.",
            "Compare mol disponíveis com coeficientes.",
            "Usar O2 como limitante sem checar a razão 2:1.",
            ["Química orgânica"],
            ["limitante", "mol"],
        ),
        (
            2020,
            "Química",
            "Química orgânica",
            "Funções",
            "qui-org",
            "O grupo –COOH ligado à cadeia carbônica, responsável pela acidez típica dos ácidos carboxílicos, associa-se a qual classe?",
            ["Éteres", "Aldeídos", "Cetonas", "Ácidos carboxílicos", "Aminas"],
            3,
            "Fácil",
            "1) –COOH = carboxila.\n2) Compostos com carboxila = ácidos carboxílicos.\n3) Aldeído –CHO; cetona C=O interna; éter R–O–R.",
            "Reconhecer grupos funcionais.",
            "COOH ⇒ ácido carboxílico.",
            "Confundir com aldeído por ter oxigênio.",
            ["Estequiometria"],
            ["carboxila", "funcao"],
        ),
        (
            2021,
            "Química",
            "Estequiometria",
            "Mol",
            "qui-est",
            "Sabendo que a massa molar aproximada do dióxido de carbono (CO2) é 44 g/mol, a quantidade de matéria correspondente a 176 g de CO2 puro, em mols, é:",
            ["2 mol", "3 mol", "4 mol", "5 mol", "6 mol"],
            2,
            "Fácil",
            "1) n = m/M.\n2) 176/44 = 4.\n3) Logo 4 mol.",
            "Conversão massa ↔ mol.",
            "Divida a massa pela massa molar.",
            "Multiplicar em vez de dividir.",
            ["Química orgânica"],
            ["massa molar", "mol"],
        ),
        (
            2018,
            "Física",
            "Cinemática",
            "MRU/MRUV",
            "fis-cin",
            "Um móvel em MRUV parte do repouso com aceleração constante de 2 m/s². A distância percorrida nos primeiros 5 s, em metros, é:",
            ["10", "20", "25", "50", "100"],
            2,
            "Média",
            "1) s = v0 t + (1/2) a t², v0=0.\n2) s = 0,5·2·25 = 25 m.\n3) Não usar v=at como distância.",
            "Equação horária do MRUV.",
            "(1/2)at² com v0=0.",
            "Calcular só velocidade final e chamar de distância.",
            ["Eletrodinâmica"],
            ["mruv", "aceleracao"],
        ),
        (
            2020,
            "Física",
            "Eletrodinâmica",
            "Circuitos",
            "fis-ele",
            "Em série, duas resistências iguais R com fonte ideal V dissipam potência total P. Religas as mesmas em paralelo à mesma fonte. A nova potência total é:",
            ["P/4", "P/2", "P", "2P", "4P"],
            4,
            "Difícil",
            "1) Série: Req=2R ⇒ P=V²/(2R).\n2) Paralelo: Req=R/2 ⇒ P'=2 V²/R = 4P.\n3) Logo 4P.",
            "Comparar potência com Req diferente.",
            "P ∝ 1/Req; Req cai 4× da série ao paralelo de dois iguais.",
            "Esquecer que a potência na fonte muda com Req.",
            ["Cinemática"],
            ["serie", "paralelo", "potencia"],
        ),
        (
            2022,
            "Física",
            "Cinemática",
            "MRU/MRUV",
            "fis-cin",
            "A parte do mesmo ponto: A em MRU com 10 m/s e B em MRUV do repouso com 2 m/s². O instante t>0 em que B alcança a posição de A pela primeira vez é:",
            ["5", "10", "15", "20", "25"],
            1,
            "Difícil",
            "1) sA=10t; sB=t².\n2) t²=10t ⇒ t(t-10)=0 ⇒ t=10 s.\n3) t=0 é a partida.",
            "Igualar equações horárias.",
            "Resolva a equação do 2º grau e descarte t=0.",
            "Usar velocidade relativa sem integrar.",
            ["Eletrodinâmica"],
            ["alcance", "mruv"],
        ),
        (
            2019,
            "Língua Portuguesa e Literatura",
            "Interpretação de texto",
            "Funções da linguagem",
            "pt-int",
            "Em um editorial que busca convencer o leitor a apoiar uma política pública de saúde, com argumentos e modalizadores de opinião, a função da linguagem em destaque é:",
            ["Referencial", "Emotiva", "Conativa (apelativa)", "Metalinguística", "Poética"],
            2,
            "Média",
            "1) Objetivo: influenciar o leitor.\n2) Função conativa/apelativa.\n3) Referencial informa; emotiva centra no emissor.",
            "Diferenciar funções pelo propósito do texto.",
            "Convencer o leitor ⇒ conativa.",
            "Marcar referencial só porque há dados.",
            ["Coesão e coerência"],
            ["conativa", "editorial"],
        ),
        (
            2020,
            "Língua Portuguesa e Literatura",
            "Coesão e coerência",
            "Conectivos",
            "pt-coe",
            'No período "O paciente aderiu ao tratamento; _____, os sintomas diminuíram em duas semanas", o conectivo que melhor expressa conclusão/resultado é:',
            ["entretanto", "ou seja", "portanto", "isto é", "embora"],
            2,
            "Fácil",
            "1) Há causa implícita e efeito.\n2) Portanto marca conclusão/resultado.\n3) Entretanto/embora contrastam; ou seja/isto é explicam.",
            "Escolher conectivo pela relação lógica.",
            "Resultado ⇒ portanto.",
            "Usar adversativo por hábito.",
            ["Interpretação de texto"],
            ["conectivo", "coesao"],
        ),
        (
            2021,
            "Língua Portuguesa e Literatura",
            "Literatura",
            "Escolas literárias",
            "pt-lit",
            "O Romantismo brasileiro, na fase indianista, frequentemente constrói o indígena como símbolo nacional. Essa operação dialoga principalmente com:",
            [
                "Objetividade científica do Naturalismo",
                "Idealização e construção de identidade nacional",
                "Ruptura completa com o sentimento",
                "Predomínio do verso livre modernista",
                "Teatro do absurdo",
            ],
            1,
            "Média",
            "1) Romantismo valoriza sentimento e nação.\n2) Indianismo idealiza o indígena como mito fundador.\n3) Naturalismo/Modernismo são estéticas distintas.",
            "Associar escola literária a projeto ideológico.",
            "Indianismo = nação idealizada.",
            "Colar atributos de outras escolas.",
            ["Interpretação de texto"],
            ["romantismo", "indianismo"],
        ),
        (
            2018,
            "História",
            "Brasil República",
            "Século XX",
            "his-br",
            "A Era Vargas (1930–1945) combinou centralização política e legislação trabalhista. Uma medida emblemática no campo do trabalho foi:",
            [
                "Abolição imediata da escravidão",
                "Criação da CLT consolidando direitos trabalhistas",
                "Privatização ampla das estatais nos anos 1930",
                "Fim do voto feminino",
                "Adoção do parlamentarismo britânico",
            ],
            1,
            "Média",
            "1) CLT (1943) consolida direitos sob Vargas.\n2) Abolição foi 1888; voto feminino avançou em 1932.\n3) Privatização ampla não descreve o estatismo varguista típico.",
            "Cronologia República e políticas sociais.",
            "Vargas + trabalho ⇒ CLT.",
            "Misturar com Império ou redemocratização posterior.",
            ["Geografia do Brasil"],
            ["vargas", "clt"],
        ),
        (
            2020,
            "Geografia",
            "Geografia do Brasil",
            "Nordeste",
            "geo-br",
            "O semiárido nordestino apresenta irregularidade pluviométrica e forte evaporação. Uma estratégia de convivência com a seca historicamente debatida é:",
            [
                "Transposição e armazenamento de água + práticas de convivência",
                "Eliminação completa da agricultura familiar",
                "Urbanização forçada de toda a zona rural",
                "Introdução de clima equatorial via geoengenharia",
                "Proibição de açudes",
            ],
            0,
            "Média",
            "1) Problema: irregularidade de chuvas.\n2) Respostas: armazenamento, gestão hídrica e convivência.\n3) Alternativas extremas não são políticas realistas.",
            "Relacionar clima semiárido e políticas hídricas.",
            "Conviver com a seca ≠ acabar com o clima.",
            "Escolher soluções milagrosas.",
            ["Brasil República"],
            ["semiarido", "seca"],
        ),
        (
            2021,
            "Filosofia",
            "Ética",
            "Teorias morais",
            "fil-eti",
            "Na ética consequencialista de Bentham e Mill, o utilitarismo clássico avalia a moralidade pelo saldo de prazer e dor. A ação moralmente correta tende a ser aquela que:",
            [
                "Obedece apenas à tradição local",
                "Maximiza a felicidade/utilidade geral",
                "Ignora consequências e foca só na intenção pura",
                "Nega qualquer cálculo de bem-estar",
                "Rejeita imparcialidade",
            ],
            1,
            "Fácil",
            "1) Utilitarismo avalia consequências em termos de utilidade.\n2) Maior bem para o maior número.\n3) Deontologia kantiana enfatiza dever de outro modo.",
            "Diferenciar utilitarismo de deontologia.",
            "Utilitarismo = consequências e utilidade agregada.",
            "Colar Kant no utilitarismo.",
            ["Cultura e sociedade"],
            ["utilitarismo", "etica"],
        ),
        (
            2022,
            "Sociologia",
            "Cultura e sociedade",
            "Identidade",
            "soc-cul",
            "Em Sociologia, o conceito de socialização descreve a interiorização de normas e valores ao longo da vida. Esse conceito designa principalmente o processo pelo qual:",
            [
                "O indivíduo nasce com papéis sociais prontos e imutáveis",
                "O indivíduo internaliza normas, valores e papéis ao longo da vida",
                "A biologia determina sozinha toda a cultura",
                "O Estado substitui completamente a família e a escola",
                "A identidade é fixada apenas no nascimento",
            ],
            1,
            "Fácil",
            "1) Socialização = aprendizado social contínuo.\n2) Família, escola, mídia etc. participam.\n3) Não é destino biológico exclusivo.",
            "Definir socialização sem biologismo.",
            "Socialização = internalizar a vida em sociedade.",
            "Tratar cultura como genética.",
            ["Ética"],
            ["socializacao", "normas"],
        ),
        (
            2017,
            "Biologia",
            "Citologia",
            "Membrana",
            "bio-cit",
            "Em osmose celular, uma célula animal (sem parede rígida) é colocada em meio hipotônico em relação ao citoplasma. Nessas condições, a célula tende a:",
            [
                "Perder água e murchar",
                "Ganhar água e aumentar de volume, podendo romper",
                "Manter volume por parede celular rígida como vegetal",
                "Produzir ATP exclusivamente por fermentação obrigatória",
                "Deixar de ter mitocôndrias",
            ],
            1,
            "Média",
            "1) Hipotônico: meio menos concentrado que o citoplasma.\n2) Água entra por osmose.\n3) Sem parede rígida, risco de lise.",
            "Osmose e tonicidade.",
            "Hipo = entra água na célula animal.",
            "Confundir com hipertônico.",
            ["Fisiologia humana"],
            ["osmose", "hipotonico"],
        ),
        (
            2017,
            "Matemática",
            "Funções",
            "Exponencial",
            "mat-fun",
            "A função exponencial g(x)=3^x - 1 é avaliada no plano cartesiano. O ponto em que essa curva corta o eixo das ordenadas é:",
            ["(0,0)", "(0,1)", "(0,2)", "(1,0)", "(1,2)"],
            2,
            "Fácil",
            "1) Em x=0, 3^0-1=0.\n2) Espera-se (0,0)? 3^0=1 ⇒ 1-1=0 ⇒ (0,0).\n3) Correção: opções — na verdade 3^0-1=0, então (0,0).",
            "Avaliar função no eixo y.",
            "x=0 ⇒ só o termo constante efetivo.",
            "Calcular 3^1 por engano.",
            ["Probabilidade"],
            ["funcao", "eixo"],
        ),
    ]
    # Fix the buggy item above - regenerate correctly
    qs: list[dict[str, Any]] = []
    i = 0
    for row in raw:
        year, subject, topic, subtopic, sid, stmt, opts, correct, diff, res, banca, mac, peg, rel, kw = row
        # Skip the known-bad g(x) item and replace
        if "g(x)=3" in stmt:
            stmt = (
                "A função exponencial g(x)=3^x - 1 é avaliada no plano cartesiano. O ponto em que essa curva corta o eixo das ordenadas (eixo y) é:"
            )
            opts = ["(0,-1)", "(0,0)", "(0,1)", "(0,2)", "(1,0)"]
            correct = 1
            res = (
                "1) Eixo y: x=0.\n"
                "2) g(0)=3^0 - 1 = 1 - 1 = 0.\n"
                "3) Ponto (0,0)."
            )
            mac = "x=0 na exponencial: base^0=1."
            peg = "Esquecer de subtrair 1 e marcar (0,1)."
        i += 1
        assert len(stmt) >= 120, stmt[:40]
        assert len(res.split("\n")) >= 3, res
        qs.append(
            _q(i, year, subject, topic, subtopic, stmt, opts, correct, diff, sid, res, banca, mac, peg, rel, kw)
        )
    # Curadoria: itens "parecidos" de outra banca — sempre rotulados OUTRA
    similar_specs = [
        (
            "sim-outra-mendel-01",
            "bio-2017-01",
            "Enunciado no estilo ENEM/vestibular genérico (NÃO é PAES-UEMA): um casal heterozigoto para um gene autossômico clássico espera a probabilidade de um filho com fenótipo recessivo. A resposta correta é a mesma da segregação Aa×Aa, mas a banca de origem não é a UEMA.",
            ["0%", "25%", "50%", "75%", "100%"],
            1,
            "Biologia",
            "Genética",
            "Mendel",
            "bio-gen",
            "1) É o mesmo monohibridismo Aa×Aa.\n2) Recessivo = aa = 1/4.\n3) Rótulo OUTRA: treino de estrutura, não prova UEMA.",
            "Similar à âncora de treino mendeliana; usar só como reforço.",
            "Aa×Aa → 25% recessivo.",
            "Tratar como se fosse oficial UEMA.",
        ),
        (
            "sim-outra-ohm-01",
            "fis-ohm-treino",
            "Questão no formato de outra banca estadual (rótulo OUTRA): resistor ôhmico sob tensão constante. Se a tensão dobra e a resistência permanece a mesma, o que ocorre com a corrente elétrica?",
            ["Permanece igual", "Dobra", "Cai pela metade", "Quadruplica", "Zera"],
            1,
            "Física",
            "Eletrodinâmica",
            "Lei de Ohm",
            "fis-ele",
            "1) I = U/R.\n2) U→2U com R fixo ⇒ I→2I.\n3) Não inventar incidência PAES: isto é similar de OUTRA banca.",
            "Parecida com itens de Ohm do treino local.",
            "Ohm: corrente proporcional à tensão.",
            "Assumir que UEMA cobrou exatamente este enunciado.",
        ),
    ]
    for sid_q, anchor, stmt, opts, correct, subject, topic, subtopic, syid, res, note, mac, peg in similar_specs:
        # anchor may not exist as id — use first bio/fis treino id pattern
        if anchor == "fis-ohm-treino":
            anchor = next((x["id"] for x in qs if x["subject"] == "Física"), qs[0]["id"] if qs else "treino-denso-001")
        if anchor == "bio-2017-01":
            # prefer core id after seed merge; expand-only fallback
            anchor = "bio-2017-01"
        i += 1
        assert len(stmt) >= 120
        q = _q(
            i,
            2024,
            subject,
            topic,
            subtopic,
            stmt,
            opts,
            correct,
            "Média",
            syid,
            res,
            "Item de outra banca para reforço de estrutura — não oficial UEMA.",
            mac,
            peg,
            [topic],
            ["similar", "outra"],
        )
        q["id"] = sid_q
        q["exam_board"] = "OUTRA"
        q["similarity_of"] = anchor
        q["similarity_note"] = note
        qs.append(q)
    return qs
